[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base="dark"
primaryColor="#6C63FF"
backgroundColor="#0A0F24"
secondaryBackgroundColor="#11182F"
textColor="#FFFFFF"
font="sans serif"
