[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[theme]
base="dark"
primaryColor="#39FF14"
backgroundColor="#000000"
secondaryBackgroundColor="#0A0A0A"
textColor="#FFFFFF"
font="sans serif"
